name: markdown-autodocs

on:
  push:
    branches:    
      - '**'        # matches every branch

jobs:        
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.3
          with:
            output_file_paths: '[./ApproachBasicBETA.md,./MaterialPointScanner.md,./MissileLauncher.md,./MiningLaserPulse.md,./GeneratorEfficiencyBasic.md]'
            categories: '[code-block]'